apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: demo
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/includeInboundPorts: "50051,8080"
    spec:
      containers:
      - name: nodejs-app
        image: 29trxngxx/nodejs-app:latest
        ports:
        - containerPort: 50051
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: "192.168.80.216"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "seta@123"
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.istio-system:14268/api/traces"
        command: ["sh", "-c", "npm install && npm start"]
