apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: 29trxngxx/nodejs-app:latest
        ports:
        - containerPort: 50051
        env:
        - name: POSTGRES_HOST
          value: "192.168.80.216"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "seta@123"
