apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nodejs-app
  namespace: demo
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: nodejs-app-service.demo.svc.cluster.local
            port:
              number: 50051
